name: Build TxtLogParser Windows Self-Hosted

on:
  workflow_dispatch:

env:
  QT_VERSION: '6.8.3'
  CMAKE_VERSION: '3.28'
  BUILD_TYPE: Release

jobs:
  build-windows:
    name: Build on Windows Self-Hosted
    runs-on: [self-hosted, Windows, X64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        set-safe-directory: false

    - name: Setup devcmd
      uses: ilammy/msvc-dev-cmd@v1

    - name: Add Git bin to PATH
      shell: cmd
      run: |
        echo "C:\Program Files\Git\usr\bin" >> %GITHUB_PATH%

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        arch: 'win64_msvc2022_64'
        modules: 'all'
        archives: 'qtbase qtsvg qttools qttranslations'
        tools: 'tools_ninja tools_cmake'
        cache: 'true'

    - name: Build
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles" -DQT_DIR=%Qt_ROOT_DIR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE%
        nmake
