name: Build TxtLogParser Windows

on:
  workflow_dispatch:

env:
  QT_VERSION: '6.8.3' # Reverted to your original version
  CMAKE_VERSION: '3.28'
  BUILD_TYPE: Release

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup devcmd
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: "6.9.0"
        arch: win64_msvc2022_64
        archives: qtbase qtsvg qttools
        cache: true

    - name: Build
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles" -DQT_DIR=%Qt_ROOT_DIR%
        nmake
