name: Build TxtLogParser Windows

on:
  workflow_dispatch:

env:
  QT_VERSION: '6.8.3'
  CMAKE_VERSION: '3.28'
  BUILD_TYPE: Release

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup devcmd
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: "6.8.0"
        arch: win64_msvc2022_64
        cache: true
        
    - name: Show Path
      shell: powershell
      run: |
        echo $env:PATH

    - name: Store Path
      shell: bash
      run: |
        echo $PATH > env_vars.txt    

    - name: Build
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%BUILD_TYPE%
        nmake
        cmake --build . --target deploy --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: envs1
        path: env_vars.txt
        retention-days: 7
